### ISSUE TITLE
Graph like behaviour

### ISSUE THREAD

**Issue by yamanyar** [rails/acts_as_list#15]
I can store a relation that is a graph in fact. Is it expected? I think it should throw an exception when it recycling. Here is the test (please note that this test passes; however i am expecting it to fail):

```
category = Category.new
category.name="Parent"
category.save
child = category.children.create("name" => "child_1")
child.children = [category]
assert category.save
loadedChild = Category.find_by_name("child_1")
assert_equal "Parent", loadedChild.parent.name
assert_equal "Parent", loadedChild.children[0].name
```

**Comment by amerine** [comment]
Hello Yamanyar,

This fork is no longer maintained. Can you post this issue at the new location:  https://github.com/swanandp/acts_as_list

Thanks,
Mark

**Comment by yamanyar** [comment]
Thanks for the update,
Cheers,
Yamanyar
